import streamlit as st
import pandas as pd
import numpy as np
import joblib
import os

# ---------------------------------------------------------
# 1. Page Configuration (Centered Layout)
# ---------------------------------------------------------
st.set_page_config(
    page_title="Robotic Surgery Difficulty Prediction",
    page_icon="🤖",
    layout="centered"
)

# ---------------------------------------------------------
# 2. Load Model and Artifacts
# ---------------------------------------------------------
@st.cache_resource
def load_artifacts():
    try:
        # Directly load files from the current directory
        # Ensure these files match the names generated by your training code
        model = joblib.load("final_ensemble_model.pkl")
        scaler = joblib.load("final_scaler.pkl")
        model_columns = joblib.load("final_feature_columns.pkl") # Critical for column alignment
        return model, scaler, model_columns
    except FileNotFoundError as e:
        st.error(f"❌ Error: Necessary files not found. Details: {e}")
        st.warning("Please ensure 'final_ensemble_model.pkl', 'final_scaler.pkl', and 'final_feature_columns.pkl' are in the same directory.")
        return None, None, None

model, scaler, model_columns = load_artifacts()

# ---------------------------------------------------------
# 3. Title and Introduction
# ---------------------------------------------------------
st.title("🤖 Robotic Surgery Difficulty Prediction Model")
st.markdown("""
This application predicts the difficulty probability of **robotic rectal surgery** based on preoperative clinical features and pelvic measurements.
Please input the patient's parameters below.
""")

st.markdown("---")

# ---------------------------------------------------------
# 4. Patient Features Input (Two-Column Layout)
# ---------------------------------------------------------
st.subheader("Patient Features Input")

if model is not None:
    with st.form("prediction_form"):
        col1, col2 = st.columns(2)

        with col1:
            # 1. Tumor size (New Feature)
            # Chinese: 肿瘤大小
            f_tumor_size = st.number_input(
                "Tumor size (cm)", 
                min_value=0.0, max_value=15.0, value=3.0, step=0.1,
                format="%.1f",
                help="Maximum diameter of the tumor."
            )

            # 2. History of abdominal surgery
            # Chinese: 腹部手术史
            f_history_display = st.selectbox(
                "History of abdominal surgery",
                options=["No", "Yes"],
                index=0,
                help="History of previous abdominal surgery."
            )
            f_history = 1 if f_history_display == "Yes" else 0
            
            # 3. Distance from anal verge
            # Chinese: 肿瘤与肛缘距离
            f_dist_anal = st.number_input(
                "Distance from anal verge (cm)", 
                min_value=0.0, max_value=20.0, value=5.0, step=0.5,
                format="%.1f",
                help="Distance from the tumor to the anal verge."
            )

        with col2:
            # 4. Sacral chord length (New Feature)
            # Chinese: 骶骨弦长
            f_sacral_chord = st.number_input(
                "Sacral chord length (cm)", 
                min_value=5.0, max_value=20.0, value=10.0, step=0.1,
                format="%.1f",
                help="Distance between the sacral promontory and the tip of the coccyx (chord length)."
            )
            
            # 5. Mesorectal fat area
            # Chinese: 直肠系膜脂肪区面积
            f_fat_area = st.number_input(
                "Mesorectal fat area (cm²)", 
                min_value=0.0, max_value=100.0, value=20.0, step=0.1,
                format="%.1f",
                help="Area of the mesorectal fat."
            )

        # Submit Button
        submit_btn = st.form_submit_button("🚀 Predict Difficulty", use_container_width=True)

    # ---------------------------------------------------------
    # 5. Prediction Logic
    # ---------------------------------------------------------
    if submit_btn:
        # --- A. Construct Input DataFrame ---
        # Keys must match the training data columns EXACTLY
        # Selected Features: ['Tumor size', 'History of abdominal surgery', 'Distance from anal verge', 'Sacral chord length', 'Mesorectal fat area']
        input_data = pd.DataFrame([{
            'Tumor size': f_tumor_size,
            'History of abdominal surgery': f_history,
            'Distance from anal verge': f_dist_anal,
            'Sacral chord length': f_sacral_chord,
            'Mesorectal fat area': f_fat_area
        }])
        
        # --- B. Data Preprocessing ---
        # 1. One-Hot Encoding
        input_df_encoded = pd.get_dummies(input_data)
        
        # 2. Column Alignment (Critical Step)
        input_df_aligned = input_df_encoded.reindex(columns=model_columns, fill_value=0)
        
        # 3. Standardization
        input_scaled = scaler.transform(input_df_aligned)
        input_scaled_df = pd.DataFrame(input_scaled, columns=model_columns)
        
        # --- C. Model Inference ---
        # Get probability for Class 1 (High Difficulty)
        probability = model.predict_proba(input_scaled_df)[0][1]
        prediction_class = 1 if probability >= 0.5 else 0
        
        # ---------------------------------------------------------
        # 6. Result Display
        # ---------------------------------------------------------
        st.markdown("---")
        st.subheader("Prediction Result")
        
        # Progress bar
        st.progress(float(probability))
        
        result_col1, result_col2 = st.columns(2)
        
        with result_col1:
            st.metric(label="Difficulty Probability", value=f"{probability:.1%}")
            
        with result_col2:
            if prediction_class == 1:
                st.error("⚠️ High Difficulty Predicted")
            else:
                st.success("✅ Low Difficulty Predicted")
                
        if probability >= 0.5:
            st.warning(f"The model predicts a **{probability:.1%}** chance of high surgical difficulty.")
        else:
            st.info(f"The model predicts a **{probability:.1%}** chance of high surgical difficulty (Low Risk).")

# --- Footer ---
st.markdown("---")
st.caption("Model based on Ensemble Learning (GaussianNB + SVM + MLP).")
